export const ADD_FORCE_MSG = 'ADD_FORCE';
export const ADD_IMPULSE_MSG = 'ADD_IMPULSE';
export const STOP_MOVEMENT_MSG = 'STOP_MOVEMENT';
export const COLLISION_MSG = 'COLLISION';
export const COLLISION_ENTER_MSG = 'COLLISION_ENTER';
export const COLLISION_STAY_MSG = 'COLLISION_STAY';
export const COLLISION_LEAVE_MSG = 'COLLISION_LEAVE';

export const GRAVITATIONAL_ACCELERATION_STORE_KEY = 'gravitationalAcceleration';
